### ISSUE TITLE
have the ethcc video on the website start at 10:44

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/website#1]
https://youtu.be/WJ23oQpooG0?t=644 is the link to use... i think

**Comment by MaxSemenchuk** [comment]
@GriffGreen can't easily insert the time start, can just cut and upload a separate one =/  would you like that?

**Comment by GriffGreen** [comment]
:-( yeah i guess so... If its not too much work. If its a lot of work, or it ends up at a low quality, maybe we should just skip the video....

**Comment by MaxSemenchuk** [comment]
Kris asked to remove the video at all =/
