### ISSUE TITLE
Add icons at the bottom to link to our resources

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#10]
This is the least urgent issue, just a nice to have: 

// aragon dac site, could you place the logos of our resources back at the bottom? you can steal them from giveth.io. For now mainly giveth resources, will change in the future

Medium: https://medium.com/giveth 
Join: https://t.me/CommonsStack  
Twitter: https://twitter.com/givethio
GitHub: https://github.com/commons-stack

**Comment by MaxSemenchuk** [comment]
@krrisis instead of Riot/Telegram we have now already? Or just add medium, twitter and github (the there would be 5 icons)

**Comment by krrisis** [comment]
I would add it on top of it yeah, keep the current ones

**Comment by MaxSemenchuk** [comment]
Added
again, want to add 5 in the row – but it's not supported from default. Can look in that a bit later if needed
