### ISSUE TITLE
Replace vid by 2 text blocks 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#11]
Could you replace the vid by 2 text blocks like we had on aragon dac?
So under the moving visual.
Plz do also check mobile optimization 

Text blocks + links here: https://docs.google.com/document/d/1wqnisIdIl1vpx4rs0clVl7iyJHyDktSzfK2xTS_iEOQ/edit?usp=sharing

**Comment by MaxSemenchuk** [comment]
Pls check

**Comment by krrisis** [comment]
great!
