### ISSUE TITLE
Replace logo with final one

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#14]
Last svg zip shared by loie in telegram

**Comment by MaxSemenchuk** [comment]
pls check

**Comment by krrisis** [comment]
Could you use the horizontal logo for the desktop website? For me the horizontal is fine for mobile as well, but if you want to mix it up (and it's possible) you could keep the vertical one for mobile. But on desktop the horizontal looks better I'd say.

**Comment by MaxSemenchuk** [comment]
switched back for horizontal

**Comment by krrisis** [comment]
great! if that is the one with the final font, this one is OK!
