### ISSUE TITLE
TOKEN SALE!!! Ummmmm no

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/website#2]
maybe we should brain storm.... i dont really want to call it out explicitly as a donation... maybe we need to change it to Supporter... this is something Abbey and I wanted to jive on for a bit. 

Until we figure out what to really call it... I suggest we say 

"Apply to be on the Common Stack Whitelist"

**Comment by MaxSemenchuk** [comment]
Changed, pls check @GriffGreen

**Comment by BvL13** [comment]
I think its simple, you apply for membership for the commons stack association.
The button should say "Apply for membership"

This button leads to the application form

The application form is a separate part of the website and has fields to fill in. 

Example of the fields can be found here:
https://docs.google.com/document/d/1abvzDg0l3hTt2FEoVNkFgmWacJwNz4XIB2hdIdtl64s/edit?usp=sharing 

By clicking on the submit button, the info is sent to a specific e-mail address of the association (e.g. membership@commonsstack.org)

The board of the association will then check the info manually

**Comment by MaxSemenchuk** [comment]
@BvL13 could you create the google form or do you ask me to do it?

**Comment by BvL13** [comment]
Sure, I can create the google form if that is the format you would like to integrate.

**Comment by MaxSemenchuk** [comment]
It's the easiest and most agile way

**Comment by BvL13** [comment]
Great. Will do.

**Comment by GriffGreen** [comment]
https://forms.gle/xPEnY41JUCZajHNN6

This is the form to link

Its a Membership Application form.

**Comment by MaxSemenchuk** [comment]
@GriffGreen @BvL13 removed KYC iframe, inserted the link to the google form
