### ISSUE TITLE
when you get to the last step you don't get notified its sent

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/website#22]
I click send and nothing happened....

Also there is a picture that isnt loading in the upperleft
<img width="1086" alt="Screen Shot 2019-06-14 at 6 30 01 PM" src="https://user-images.githubusercontent.com/14945613/59523821-92485100-8ed2-11e9-899e-4a965859222c.png">

**Comment by GriffGreen** [comment]
ok so i tried KYC 1 and i see that i can click send, i just need a pop up window or something to tell me that it worked ;-D

**Comment by BvL13** [comment]
Answer from Mt. Pelerin:
" I could not reproduce it. Normally, when you click send, you see a progress bar that will disappear and display a confirmation message. Do you have more information so that I can reproduce it ?"

**Comment by GriffGreen** [comment]
Weird it does work now... there is just a slow delay and then the progress bar goes.
