### ISSUE TITLE
Put actual code in this repository

### ISSUE THREAD

**Issue by geleeroyale** [commons-stack/website#25]
Currently, I don't have any clue where and how the website is hosted. This repo is just used as issue list. In order to transform from one person operation to open source git flow, please take necessary steps to expose code and set up permissioned CI - I will gladly help and take on some accountability.

**Comment by MaxSemenchuk** [comment]
@geleeroyale the website is hosted on https://tilda.cc
me and @krrisis have access, can provide if needed

**Comment by krrisis** [comment]
yeah, as discussed - not a priority to recreate the website in a built-from-scratch open-source format until we are sure we have funding to go through the various iterations of the commons stack. Until then we're ok to continue with Tilda and the current website should suffice.

**Comment by geleeroyale** [comment]
Not saying we need to rebuild everything from scratch, but I could help a lot with adding/editing stuff as well.

EDIT: Got the credentials via @krrisis - thanks. Will close this issue for now 🙌
