### ISSUE TITLE
create a redirect url 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#27]
could you create a url, i.e commonsstack.org/apply and have this redirect to the form directly? (https://docs.google.com/forms/d/e/1FAIpQLSfgPzuphswbr5il-_4R73NGZzP1iyXdzAKd1VtdLz1n2-mf4Q/viewform)

then we can use that url as a call to action in presentations.. thx!

**Comment by MaxSemenchuk** [comment]
Ready http://commonsstack.org/apply @krrisis

**Comment by krrisis** [comment]
thx a lot max!
