### ISSUE TITLE
Change background 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#6]
Just talked with kay, loie, griff etc
We think the background is cool but we prefer something slightly less.. psychedelic :) but NOT corporate ofc 

Proposal: could you come up with a static background that brings back some of the color coding of the carrot? 

FYI: don't put tooo much time in it, bcs that research group from the other max is working on a logo & house style. (just might still take some time - so this is for in the meantime)

**Comment by MaxSemenchuk** [comment]
@krrisis check now

**Comment by krrisis** [comment]
Really like this - perfect until the new logo is ready to be implemented!

**Comment by loietaylor** [comment]
let's color match the background to the new logo!

**Comment by MaxSemenchuk** [comment]
@lorelei1 better now?

**Comment by krrisis** [comment]
Tbh I preferred how it was, it was more subtle, less 'intense' and I don't think the colors were so out of sync. 
Do you happen to have something that resembles what was there but then in blue/green? If not I think you can stick with what's there currently. Checked with @lorelei1 and she concurs :)

**Comment by krrisis** [comment]
Ps. on mobile it does not work, so prob best to check what the best - fixed background could be on mobile

**Comment by MaxSemenchuk** [comment]
added static pic for mobile

**Comment by krrisis** [comment]
Great for mobile! 
Did you see the one above? Right now it show wrong in chrome anyways (a strange yt field)

Tbh I preferred how it was, it was more subtle, less 'intense' and I don't think the colors were so out of sync.
Do you happen to have something that resembles what was there but then in blue/green? If not I think you can stick with what's there currently. Checked with @lorelei1 and she concurs :)

**Comment by MaxSemenchuk** [comment]
@krrisis can you make a screenshot?

on the background – did you mean orange dots animation? You just want it recolored to blue/green?

**Comment by krrisis** [comment]
It might be a cache thing, see screenshot below. In incognito mode I see it correctly. 
Just wanted to flag it - but seems just me.

Re: Background, yes, the previous one, these dots bumping around lower in the animation, not so 'present' (bit distracting). Recoloring would be perfect!

![image](https://user-images.githubusercontent.com/6533925/58823357-c0f43b00-8639-11e9-8534-d8018d61c6db.png)

**Comment by krrisis** [comment]
By the way Max, personally I wouldn't mind to just have a dark background on the website if recoloring that vid takes a lot of time. Extra arguments for this 1) it looks good :)  2) on brave browser the background vid does not autoplay. And in our audience we might have some brave browser users... But not a hard opinion on it.

**Comment by MaxSemenchuk** [comment]
switched to black. Is that what you wanted or smth else?

**Comment by krrisis** [comment]
I like it. More focus on the logo, more powerful/robust.

**Comment by krrisis** [comment]
approved by the others as well in the call!
